export const environment = {
    title:'PeekNshop',
    subtitle:'choose where to shop?',
    isLocation:true,
    lat  : "",
    lon : "",
    searchText : "",
    storesSearchText:"",
    selectedStore:"",
    isLogin: false,
    storeId:"",
    city:"Gainesville",
    id:"",
    fullname:"",
    firstname:"",
    lastname:"",
    email:"",
    phone:"",
    password:"",
    accesskey:"",
    refreshkey:"",
    address1:"",
    address2:"",
    address3:""
}