export const environment = {
    title:'PeekNshop',
    subtitle:'choose where to shop?',
    isLocation:true,
    lat  : "",
    lon : "",
    searchText : "",
    storesSearchText:"",
    isLogin: true,
    city:"New York",
    id:"",
    fullname:"",
    firstname:"",
    lastname:"",
    email:"",
    password:"",
    accesskey:"",
    refreshkey:"",
    address1:"",
    address2:"",
    address3:""
}